version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    labels:
      name: container-shashank1
    volumes:
      - ./inputFile:/csvserver/inputdata    
    ports:
      - "9393:9300"
  prometheus_server:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
     - '9090:9090'
    #command: docker cp ~/infracloud/csvserver/solution/docker/inputFile inputdata prometheus:9090/metrics/
    
