version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    labels:
      name: container-shashank1
    volumes:
      - ./inputFile:/csvserver/inputdata    
    ports:
      - "9393:9300"

